"""src/understanding — Document understanding, evidence modeling, and provenance."""
from src.understanding.evidence import (
    Evidence,
    EvidenceProvenance,
    EvidenceSource,
    PageEvidence,
    generate_evidence_id,
    native_page_text_to_evidence,
    ocr_block_to_evidence,
    ocr_json_to_page_evidence,
    page_ocr_result_to_evidence,
    validate_source,
    vision_observation_to_evidence,
    vision_response_to_evidence,
)
from src.understanding.page_classifier import (
    PageRole,
    PayableRelevance,
    PageUnderstanding,
    classify_page,
)
from src.understanding.document_grouper import (
    DocumentGroup,
    GroupingResult,
    group_document,
)
from src.understanding.qwen_router import (
    RouterDecisionType,
    RoutingDecision,
    execute_vision_escalation,
    route_page,
)
from src.understanding.document_facts import (
    BuyerIdentityFact,
    ChargeFact,
    DiscountFact,
    DocumentFacts,
    DocumentIdentityFacts,
    FactOrigin,
    FinancialFacts,
    InvoiceType,
    LineFact,
    PartyIdentityFacts,
    Placement,
    POFacts,
    PrintedTotalsFact,
    SemanticRole,
    SupplierIdentityFact,
    TaxFact,
    to_decimal,
)

__all__ = [
    "BuyerIdentityFact",
    "ChargeFact",
    "DiscountFact",
    "DocumentFacts",
    "DocumentGroup",
    "DocumentIdentityFacts",
    "Evidence",
    "EvidenceProvenance",
    "EvidenceSource",
    "FactOrigin",
    "FinancialFacts",
    "GroupingResult",
    "InvoiceType",
    "LineFact",
    "PageEvidence",
    "PageRole",
    "PartyIdentityFacts",
    "PayableRelevance",
    "PageUnderstanding",
    "Placement",
    "POFacts",
    "PrintedTotalsFact",
    "RouterDecisionType",
    "RoutingDecision",
    "SemanticRole",
    "SupplierIdentityFact",
    "TaxFact",
    "classify_page",
    "execute_vision_escalation",
    "generate_evidence_id",
    "group_document",
    "native_page_text_to_evidence",
    "ocr_block_to_evidence",
    "ocr_json_to_page_evidence",
    "page_ocr_result_to_evidence",
    "route_page",
    "to_decimal",
    "validate_source",
    "vision_observation_to_evidence",
    "vision_response_to_evidence",
]

